In [46]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import statsmodels.stats.api as sms
import matplotlib as mpl
import seaborn as sns
from math import ceil

In [47]:
df = pd.read_csv('learningSet.csv')
df

C:\Users\shakt\AppData\Local\Temp\ipykernel_9160\3708753459.py:1: DtypeWarning: Columns (8) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('learningSet.csv')

,ODATEDW,OSOURCE,TCODE,STATE,ZIP,MAILCODE,PVASTATE,DOB,NOEXCH,RECINHSE,...,TARGET_D,HPHONE_D,RFA_2R,RFA_2F,RFA_2A,MDMAUD_R,MDMAUD_F,MDMAUD_A,CLUSTER2,GEOCODE2
0,8901,GRI,0,IL,61081,,,3712,0,,...,0.0,0,L,4,E,X,X,X,39.0,C
1,9401,BOA,1,CA,91326,,,5202,0,,...,0.0,0,L,2,G,X,X,X,1.0,A
2,9001,AMH,1,NC,27017,,,0,0,,...,0.0,1,L,4,E,X,X,X,60.0,C
3,8701,BRY,0,CA,95953,,,2801,0,,...,0.0,1,L,4,E,X,X,X,41.0,C
4,8601,,0,FL,33176,,,2001,0,X,...,0.0,1,L,2,F,X,X,X,26.0,A
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95407,9601,ASE,1,AK,99504,,,0,0,,...,0.0,0,L,1,G,X,X,X,12.0,C
95408,9601,DCD,1,TX,77379,,,5001,0,,...,0.0,1,L,1,F,X,X,X,2.0,A
95409,9501,MBC,1,MI,48910,,,3801,0,,...,0.0,1,L,3,E,X,X,X,34.0,B
95410,8601,PRV,0,CA,91320,,,4005,0,X,...,18.0,1,L,4,F,X,X,X,11.0,A
95411,8801,MCC,2,NC,28409,,,1801,0,X,...,0.0,1,L,1,G,C,1,C,12.0,C

In [48]:
df.shape

(95412, 481)

In [49]:
categorical = df.select_dtypes([object])
categorical

,OSOURCE,STATE,ZIP,MAILCODE,PVASTATE,NOEXCH,RECINHSE,RECP3,RECPGVG,RECSWEEP,...,RFA_21,RFA_22,RFA_23,RFA_24,RFA_2R,RFA_2A,MDMAUD_R,MDMAUD_F,MDMAUD_A,GEOCODE2
0,GRI,IL,61081,,,0,,,,,...,S4E,S4E,S4E,S4E,L,E,X,X,X,C
1,BOA,CA,91326,,,0,,,,,...,N1E,N1E,,F1E,L,G,X,X,X,A
2,AMH,NC,27017,,,0,,,,,...,,S4D,S4D,S3D,L,E,X,X,X,C
3,BRY,CA,95953,,,0,,,,,...,A1D,A1D,,,L,E,X,X,X,C
4,,FL,33176,,,0,X,X,,,...,A3D,I4E,A3D,A3D,L,F,X,X,X,A
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95407,ASE,AK,99504,,,0,,,,,...,,,,,L,G,X,X,X,C
95408,DCD,TX,77379,,,0,,,,,...,,,,,L,F,X,X,X,A
95409,MBC,MI,48910,,,0,,X,,,...,P1D,P1D,,,L,E,X,X,X,B
95410,PRV,CA,91320,,,0,X,,,,...,A1F,A1F,S2F,S3F,L,F,X,X,X,A
95411,MCC,NC,28409,,,0,X,,X,,...,S3G,S3G,S3G,S3G,L,G,C,1,C,C

In [50]:
categorical.isnull().all()

OSOURCE     False
STATE       False
ZIP         False
MAILCODE    False
PVASTATE    False
            ...
RFA_2A      False
MDMAUD_R    False
MDMAUD_F    False
MDMAUD_A    False
GEOCODE2    False
Length: 74, dtype: bool

In [51]:
count = categorical.isnull().sum()
count

OSOURCE       0
STATE         0
ZIP           0
MAILCODE      0
PVASTATE      0
           ...
RFA_2A        0
MDMAUD_R      0
MDMAUD_F      0
MDMAUD_A      0
GEOCODE2    132
Length: 74, dtype: int64

In [52]:
drop_list = []

In [53]:
drop_list.append(['OSOURCE','ZIP'])

In [54]:
drop_list

[['OSOURCE', 'ZIP']]

In [55]:
categorical_copy = categorical.copy()
print(categorical_copy.columns)

Index(['OSOURCE', 'STATE', 'ZIP', 'MAILCODE', 'PVASTATE', 'NOEXCH', 'RECINHSE',
       'RECP3', 'RECPGVG', 'RECSWEEP', 'MDMAUD', 'DOMAIN', 'CLUSTER',
       'AGEFLAG', 'HOMEOWNR', 'CHILD03', 'CHILD07', 'CHILD12', 'CHILD18',
       'GENDER', 'DATASRCE', 'SOLP3', 'SOLIH', 'MAJOR', 'GEOCODE', 'COLLECT1',
       'VETERANS', 'BIBLE', 'CATLG', 'HOMEE', 'PETS', 'CDPLAY', 'STEREO',
       'PCOWNERS', 'PHOTO', 'CRAFTS', 'FISHER', 'GARDENIN', 'BOATS', 'WALKER',
       'KIDSTUFF', 'CARDS', 'PLATES', 'LIFESRC', 'PEPSTRFL', 'RFA_2', 'RFA_3',
       'RFA_4', 'RFA_5', 'RFA_6', 'RFA_7', 'RFA_8', 'RFA_9', 'RFA_10',
       'RFA_11', 'RFA_12', 'RFA_13', 'RFA_14', 'RFA_15', 'RFA_16', 'RFA_17',
       'RFA_18', 'RFA_19', 'RFA_20', 'RFA_21', 'RFA_22', 'RFA_23', 'RFA_24',
       'RFA_2R', 'RFA_2A', 'MDMAUD_R', 'MDMAUD_F', 'MDMAUD_A', 'GEOCODE2'],
      dtype='object')

In [56]:

columns_to_drop = [col[0] for col in drop_list]
categorical_copy = categorical_copy.drop(columns=columns_to_drop)
categorical_copy

,STATE,ZIP,MAILCODE,PVASTATE,NOEXCH,RECINHSE,RECP3,RECPGVG,RECSWEEP,MDMAUD,...,RFA_21,RFA_22,RFA_23,RFA_24,RFA_2R,RFA_2A,MDMAUD_R,MDMAUD_F,MDMAUD_A,GEOCODE2
0,IL,61081,,,0,,,,,XXXX,...,S4E,S4E,S4E,S4E,L,E,X,X,X,C
1,CA,91326,,,0,,,,,XXXX,...,N1E,N1E,,F1E,L,G,X,X,X,A
2,NC,27017,,,0,,,,,XXXX,...,,S4D,S4D,S3D,L,E,X,X,X,C
3,CA,95953,,,0,,,,,XXXX,...,A1D,A1D,,,L,E,X,X,X,C
4,FL,33176,,,0,X,X,,,XXXX,...,A3D,I4E,A3D,A3D,L,F,X,X,X,A
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95407,AK,99504,,,0,,,,,XXXX,...,,,,,L,G,X,X,X,C
95408,TX,77379,,,0,,,,,XXXX,...,,,,,L,F,X,X,X,A
95409,MI,48910,,,0,,X,,,XXXX,...,P1D,P1D,,,L,E,X,X,X,B
95410,CA,91320,,,0,X,,,,XXXX,...,A1F,A1F,S2F,S3F,L,F,X,X,X,A
95411,NC,28409,,,0,X,,X,,C1CM,...,S3G,S3G,S3G,S3G,L,G,C,1,C,C

In [60]:
for col in categorical_copy.columns:
    pct_missing = np.mean(categorical_copy[col].isnull())
    print('{} - {}%'.format(col, round(pct_missing*100)))

STATE - 0%
ZIP - 0%
MAILCODE - 0%
PVASTATE - 0%
NOEXCH - 0%
RECINHSE - 0%
RECP3 - 0%
RECPGVG - 0%
RECSWEEP - 0%
MDMAUD - 0%
DOMAIN - 0%
CLUSTER - 0%
AGEFLAG - 0%
HOMEOWNR - 0%
CHILD03 - 0%
CHILD07 - 0%
CHILD12 - 0%
CHILD18 - 0%
GENDER - 0%
DATASRCE - 0%
SOLP3 - 0%
SOLIH - 0%
MAJOR - 0%
GEOCODE - 0%
COLLECT1 - 0%
VETERANS - 0%
BIBLE - 0%
CATLG - 0%
HOMEE - 0%
PETS - 0%
CDPLAY - 0%
STEREO - 0%
PCOWNERS - 0%
PHOTO - 0%
CRAFTS - 0%
FISHER - 0%
GARDENIN - 0%
BOATS - 0%
WALKER - 0%
KIDSTUFF - 0%
CARDS - 0%
PLATES - 0%
LIFESRC - 0%
PEPSTRFL - 0%
RFA_2 - 0%
RFA_3 - 0%
RFA_4 - 0%
RFA_5 - 0%
RFA_6 - 0%
RFA_7 - 0%
RFA_8 - 0%
RFA_9 - 0%
RFA_10 - 0%
RFA_11 - 0%
RFA_12 - 0%
RFA_13 - 0%
RFA_14 - 0%
RFA_15 - 0%
RFA_16 - 0%
RFA_17 - 0%
RFA_18 - 0%
RFA_19 - 0%
RFA_20 - 0%
RFA_21 - 0%
RFA_22 - 0%
RFA_23 - 0%
RFA_24 - 0%
RFA_2R - 0%
RFA_2A - 0%
MDMAUD_R - 0%
MDMAUD_F - 0%
MDMAUD_A - 0%
GEOCODE2 - 0%

In [63]:

for col in categorical_copy.columns:
    pct_missing = np.mean(categorical_copy[col].isnull())
    if pct_missing > 0.85:
        print('{} - {}%'.format(col, round(pct_missing * 100)))

In [66]:
# No missing value , so we do not need to drop any column

In [67]:
print(categorical_copy['GENDER'].value_counts())
categorical_copy['GENDER'] = categorical_copy['GENDER'].fillna('F')

GENDER
F    51277
M    39094
      2957
U     1715
J      365
C        2
A        2
Name: count, dtype: int64

In [70]:

categorical_copy['GENDER'] = categorical_copy['GENDER'].fillna('F')

categorical_copy['GENDER'] = categorical_copy['GENDER'].apply(lambda x: 'other' if x not in ['M', 'F'] else x)

print(categorical_copy['GENDER'].value_counts())

GENDER
F        51277
M        39094
other     5041
Name: count, dtype: int64